language: node_js
script: 
 - npm install -g istanbul codeclimate-test-reporter
 - make cover
 - CODECLIMATE_REPO_TOKEN=d3aad610220b6eaf4f51e38393c1b62586b1d68b898b42e418d9c2a8e0a7cb0d codeclimate < coverage/lcov.info
node_js:
  - '0.10'
